// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoNutricional.App.Persistencia;

namespace SeguimientoNutricional.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.HistorialRecomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("RegistroRecomendacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroRecomendacionId");

                    b.ToTable("HistorialRecomendacion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.HistorialValoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("RegistroValoracionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroValoracionId");

                    b.ToTable("HistorialValoracion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Recomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recomendacion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("CaloriasConsumidas")
                        .HasColumnType("real");

                    b.Property<float>("Estatura")
                        .HasColumnType("real");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<float>("Imc")
                        .HasColumnType("real");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Valoracion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Coach", b =>
                {
                    b.HasBaseType("SeguimientoNutricional.App.Dominio.Persona");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TarjetaProfesional")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Nutricionista", b =>
                {
                    b.HasBaseType("SeguimientoNutricional.App.Dominio.Persona");

                    b.Property<int?>("HistorialRecomendacionId")
                        .HasColumnType("int")
                        .HasColumnName("Nutricionista_HistorialRecomendacionId");

                    b.Property<int?>("HistorialValoracionId")
                        .HasColumnType("int")
                        .HasColumnName("Nutricionista_HistorialValoracionId");

                    b.Property<int?>("RecomendacionId")
                        .HasColumnType("int");

                    b.Property<string>("TajertaProfesional")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("HistorialRecomendacionId");

                    b.HasIndex("HistorialValoracionId");

                    b.HasIndex("RecomendacionId");

                    b.HasDiscriminator().HasValue("Nutricionista");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Paciente", b =>
                {
                    b.HasBaseType("SeguimientoNutricional.App.Dominio.Persona");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("HistorialRecomendacionId")
                        .HasColumnType("int");

                    b.Property<int?>("HistorialValoracionId")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<int?>("NutricionistaId")
                        .HasColumnType("int");

                    b.Property<int?>("ValoracionId")
                        .HasColumnType("int");

                    b.HasIndex("CoachId");

                    b.HasIndex("HistorialRecomendacionId");

                    b.HasIndex("HistorialValoracionId");

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("ValoracionId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.HistorialRecomendacion", b =>
                {
                    b.HasOne("SeguimientoNutricional.App.Dominio.Recomendacion", "RegistroRecomendacion")
                        .WithMany()
                        .HasForeignKey("RegistroRecomendacionId");

                    b.Navigation("RegistroRecomendacion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.HistorialValoracion", b =>
                {
                    b.HasOne("SeguimientoNutricional.App.Dominio.Valoracion", "RegistroValoracion")
                        .WithMany()
                        .HasForeignKey("RegistroValoracionId");

                    b.Navigation("RegistroValoracion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Nutricionista", b =>
                {
                    b.HasOne("SeguimientoNutricional.App.Dominio.HistorialRecomendacion", "HistorialRecomendacion")
                        .WithMany()
                        .HasForeignKey("HistorialRecomendacionId");

                    b.HasOne("SeguimientoNutricional.App.Dominio.HistorialValoracion", "HistorialValoracion")
                        .WithMany()
                        .HasForeignKey("HistorialValoracionId");

                    b.HasOne("SeguimientoNutricional.App.Dominio.Recomendacion", "Recomendacion")
                        .WithMany()
                        .HasForeignKey("RecomendacionId");

                    b.Navigation("HistorialRecomendacion");

                    b.Navigation("HistorialValoracion");

                    b.Navigation("Recomendacion");
                });

            modelBuilder.Entity("SeguimientoNutricional.App.Dominio.Paciente", b =>
                {
                    b.HasOne("SeguimientoNutricional.App.Dominio.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("SeguimientoNutricional.App.Dominio.HistorialRecomendacion", "HistorialRecomendacion")
                        .WithMany()
                        .HasForeignKey("HistorialRecomendacionId");

                    b.HasOne("SeguimientoNutricional.App.Dominio.HistorialValoracion", "HistorialValoracion")
                        .WithMany()
                        .HasForeignKey("HistorialValoracionId");

                    b.HasOne("SeguimientoNutricional.App.Dominio.Nutricionista", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId");

                    b.HasOne("SeguimientoNutricional.App.Dominio.Valoracion", "Valoracion")
                        .WithMany()
                        .HasForeignKey("ValoracionId");

                    b.Navigation("Coach");

                    b.Navigation("HistorialRecomendacion");

                    b.Navigation("HistorialValoracion");

                    b.Navigation("Nutricionista");

                    b.Navigation("Valoracion");
                });
#pragma warning restore 612, 618
        }
    }
}
